from FeatureExtract import KeywordCount 
    def outputFeatures(fname):
        t = KeywordCount(fname)
        t.updateWordCount()
        t.updateKeywordStatistics()
        f = open('Feature'+t.name,'w')
        f.write('File name: ' + t.name + '\n')
        f.write('========================================================================================' + '\n')
        f.write('Object: ' + 'Overall' + '\n')
        f.write('========================================================================================' + '\n')
        f.write('Keyword Dictionary:' + '\n')
        f.write(str(t.keywordCTS))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('========================================================================================' + '\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 1: times(int) certain keyword appears in the transcript ' + '\n')
        f.write(str(t.keywordStat))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 2: locations(list of floats) certain keyword appears in the transcrip' + '\n')
        f.write(str(t.keywordLoc))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 3: percentage per keyword from all keywords' + '\n')
        f.write(str(t.keywordPart))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 4: percentage of all keywords from all words' + '\n')
        f.write(str(t.keywordPer))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 5: questionmarks count' + '\n')
        f.write(str(t.questionStat))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 6: questionmarks location' + '\n')
        f.write(str(t.questionLoc))
        f.write('\n')
        f.write('========================================================================================' + '\n')
        f.write('Feature 7: percentage of sentences ending with questionmark from all sentences' + '\n')
        f.write(str(t.questionPer))
        f.write('\n')
        f.close()